name: Build DutyManager AAB with Stable Environment

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # ধাপ ১: আপনার রিপোজিটরির সমস্ত ফাইল চেকআউট করা
    - name: Checkout repository
      uses: actions/checkout@v4

    # ধাপ ২: একটি স্থিতিশীল এবং পরীক্ষিত ডকার ইমেজ ব্যবহার করে AAB তৈরি করা
    - name: Build Android App Bundle (AAB) using cordova-ci
      # আমরা আর beevelop/cordova ব্যবহার করছি না
      uses: cordova-ci/cordova-android@v1.2.0
      with:
        # এই অ্যাকশনটি স্বয়ংক্রিয়ভাবে আপনার config.xml অনুযায়ী একটি AAB তৈরি করবে
        build: bundle
        
    # ধাপ ৩: সঠিক লোকেশন থেকে তৈরি হওয়া AAB ফাইলটি আপলোড করা
    - name: Upload AAB as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DutyManager-AAB
        # এই অ্যাকশনটি স্বয়ংক্রিয়ভাবে সঠিক পাথে AAB তৈরি করে
        path: platforms/android/app/build/outputs/bundle/release/app-release.aab
