name: Build DutyManager APK

on:
  push:
    branches: [ "main" ] # আপনার রিপোজিটরির ব্রাঞ্চের নাম main
  workflow_dispatch: # ম্যানুয়ালি চালানোর জন্য

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Java and Node.js
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Cordova
      run: npm install -g cordova

    - name: Create Cordova Project and Build
      run: |
        # প্রজেক্ট তৈরি
        cordova create build_folder com.belal.dutymanager DutyManager
        
        # নতুন ফোল্ডারে প্রবেশ
        cd build_folder
        
        # আপনার আপলোড করা ফাইলগুলো কপি করা
        cp ../config.xml ../index.html ../icon.png ../splash.png www/
        
        # অ্যান্ড্রয়েড প্ল্যাটফর্ম যোগ করা
        cordova platform add android@12
        
        # অ্যাপ বিল্ড করা
        cordova build android

    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: DutyManager-APK
        path: build_folder/platforms/android/app/build/outputs/apk/debug/app-debug.apk
