name: Build Signed Release APK  # <-- এটি হলো পুরো Workflow-এর নাম

jobs:                          # <-- এখানে কাজের তালিকা শুরু
  build:                       # <-- এটি হলো আমাদের মূল কাজের (Job) নাম
    runs-on: ubuntu-latest     # <-- এই কাজটি কোন কম্পিউটারে চলবে

    steps:                     # <-- এখানে কাজের ধাপগুলো (Steps) শুরু
    - name: Checkout repository # <-- ধাপ ১ এর নাম
      uses: actions/checkout@v4

    - name: Set up JDK 11      # <-- ধাপ ২ এর নাম
      uses: actions/setup-java@v4
      # ...

    - name: Build and Sign APK # <-- ধাপ ৩ এর নাম (আপনার জিজ্ঞাসিত নামটি)
      env:
        # ...
      run: |
        # ... (এখানে মূল কমান্ডগুলো চলে)

    - name: Upload Signed APK as Artifact # <-- ধাপ ৪ এর নাম
      uses: actions/upload-artifact@v4
      # ...
