name: Build DutyManager App APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    - name: Build Android APK using Docker and Gradle
      run: |
        docker run --rm -v "$(pwd)":/app -w /app beevelop/cordova:latest bash -c "
          # ধাপ ১: কর্ডোভা প্রজেক্ট তৈরি করা (এটি ঠিকমতো কাজ করছে)
          cordova create build_folder com.belal.dutymanager DutyManager &&
          cd build_folder &&
          cp ../config.xml ../index.html ../icon.png ../splash.png www/ &&
          cordova platform add android &&
          
          # ধাপ ২: সরাসরি Gradle ব্যবহার করে APK তৈরি করা (চূড়ান্ত সমাধান)
          cd platforms/android &&
          chmod +x gradlew &&
          ./gradlew assembleRelease
        "
      
    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DutyManager-APK
        path: build_folder/platforms/android/app/build/outputs/apk/release/app-release.apk
