name: Build Signed Release APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.4'

    - name: Install Android SDK and Build Tools
      run: |
        echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-33" "build-tools;33.0.2"

    - name: Build and Sign APK
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: |
        npm install -g cordova
        cordova create build_folder com.belal.dutymanager DutyManager
        cd build_folder
        cp ../config.xml ../index.html ../icon.png ../splash.png www/
        cordova platform add android@12
        keytool -genkey -v -keystore release-key.keystore -alias $KEY_ALIAS -keyalg RSA -keysize 2048 -validity 10000 -storepass $KEYSTORE_PASSWORD -keypass $KEY_PASSWORD -dname "CN=Md Belal Hossain, OU=Development, O=Belal Apps, L=Dhaka, S=Dhaka, C=BD" -noprompt
        echo '{ "android": { "release": { "keystore": "release-key.keystore", "storePassword": "'$KEYSTORE_PASSWORD'", "alias": "'$KEY_ALIAS'", "password": "'$KEY_PASSWORD'" } } }' > build.json
        
        # আমরা এখন --apk কমান্ড যোগ করছি এবং --bundle বাদ দিচ্ছি
        cordova build android --release -- --buildConfig=build.json --apk

    - name: Upload Signed APK as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DutyManager-Signed-APK
        path: build_folder/platforms/android/app/build/outputs/apk/release/app-release-signed.apk
